server.port=8080
spring.application.name=tripgenie-ai
spring.web.resources.static-locations=classpath:/static/
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
logging.level.com.astratravel=INFO
